api-version: '1.21'
name: bookshelf-inspector
version: 1.0.0-SNAPSHOT
main: dev.cgs.bookshelfinspector.BookshelfPlugin
description: Tooltips for chiseled bookshelves on action bar
load: STARTUP
authors:
- cgsdev0
